version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
        volumes:
            - ./code:/var/www/html
            - ./docker/nginx/logs:/var/log/nginx
            - ./docker/nginx/sites/default:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/snippets:/etc/nginx/snippets
            - ./docker/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
        networks:
            - core-network

    php:
        image: php:fpm
        volumes:
            - ./code:/var/www/html
        networks:
            - core-network

    mysql:
        image: 'mariadb'
        ports:
            - 8082:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - core-network

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        restart: always
        ports:
            - 8081:80
        links:
            - mysql:mysql
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: secret
            PMA_HOST: mysql
        networks:
            - core-network

networks:
    core-network:
        driver: bridge
